package main

// `lexicon distance` — compute molecular distance between molecules.
// Three forms:
//
//	lexicon distance <id-1> <id-2>      pairwise breakdown
//	lexicon distance --all [-k N]       full nearest-neighbor map
//	lexicon distance --markdown         emit molecular-neighbors.md
//
// Distance is a weighted combination of:
//   - Jaccard distance over `decomposes-into:` atom sets
//   - Zhang-Shasha tree-edit distance over parsed `assembly:` trees
//   - Type-signature mismatch (0 or 1 on type-in / type-out)
//
// Default weights match the round-2 implementation plan
// (atom=1.0, assembly=1.0, type=0.5); flags expose them so neighbors
// can be examined under multiple weightings rather than committing
// to a single number in v0.

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/justinstimatze/lexicon/render/internal/assembly"
	"github.com/justinstimatze/lexicon/render/internal/loader"
	"github.com/justinstimatze/lexicon/render/internal/types"
)

func cmdDistance(renderDir string, args []string) {
	fl := flag.NewFlagSet("distance", flag.ExitOnError)
	all := fl.Bool("all", false, "print top-k neighbors for every molecule with assembly or decomposes-into")
	topK := fl.Int("k", 3, "number of nearest neighbors to print (with --all)")
	wAtom := fl.Float64("w-atom", 1.0, "weight on Jaccard atom-set distance")
	wAsm := fl.Float64("w-assembly", 1.0, "weight on tree-edit distance")
	wType := fl.Float64("w-type", 0.5, "weight on type-signature mismatch")
	asMarkdown := fl.Bool("markdown", false, "emit neighbor map as markdown to stdout")
	fl.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage:")
		fmt.Fprintln(os.Stderr, "  lexicon distance <id-1> <id-2>          pairwise breakdown")
		fmt.Fprintln(os.Stderr, "  lexicon distance --all [-k N]           top-k neighbors per molecule")
		fmt.Fprintln(os.Stderr, "  lexicon distance --markdown [-k N]      molecular-neighbors.md output")
		fl.PrintDefaults()
	}
	_ = fl.Parse(args)

	elementsDir := filepath.Join(renderDir, "..", "elements")
	sub, err := loader.LoadAll(elementsDir)
	if err != nil {
		fatal("load elements: %v", err)
	}
	w := assembly.Weights{Atom: *wAtom, Assembly: *wAsm, Type: *wType}

	switch {
	case *all || *asMarkdown:
		printAllNeighbors(sub, w, *topK, *asMarkdown)
	case fl.NArg() == 2:
		printPairwise(sub, fl.Arg(0), fl.Arg(1), w)
	default:
		fl.Usage()
		os.Exit(2)
	}
}

func printPairwise(sub map[string]*types.LexEntry, idA, idB string, w assembly.Weights) {
	a, ok := sub[idA]
	if !ok {
		fatal("no entry %s", idA)
	}
	b, ok := sub[idB]
	if !ok {
		fatal("no entry %s", idB)
	}
	d := assembly.MolecularDistance(a, b)
	score := d.Combined(w)
	fmt.Printf("%s ↔ %s\n", idA, idB)
	fmt.Printf("  Jaccard atoms:   %.3f  (w_atom=%.2f)\n", d.Jaccard, w.Atom)
	fmt.Printf("  Tree-edit (TED): %d   (w_assembly=%.2f)\n", d.TED, w.Assembly)
	fmt.Printf("  Type mismatch:   %d   (w_type=%.2f)\n", d.TypeMismatch, w.Type)
	fmt.Printf("  Combined score:  %.3f\n", score)
}

// hostsWithComposition returns ids of elements entries that have
// either an assembly: or a decomposes-into: field, sorted ascending.
// These are the only meaningful comparison subjects.
func hostsWithComposition(sub map[string]*types.LexEntry) []string {
	var out []string
	for id, e := range sub {
		if e.Assembly != "" || len(e.DecomposesInto) > 0 {
			out = append(out, id)
		}
	}
	sort.Strings(out)
	return out
}

func printAllNeighbors(sub map[string]*types.LexEntry, w assembly.Weights, k int, asMarkdown bool) {
	hosts := hostsWithComposition(sub)
	if asMarkdown {
		fmt.Println("# molecular-neighbors")
		fmt.Println("")
		fmt.Printf("Generated by `lexicon distance --markdown -k %d`. Distance = "+
			"`%.2f·Jaccard(atoms) + %.2f·TED(assembly) + %.2f·type-mismatch`.\n\n",
			k, w.Atom, w.Assembly, w.Type)
		fmt.Println("- **Jaccard** is symmetric-difference / union over `decomposes-into:` atom sets, in [0, 1].")
		fmt.Println("- **TED** is Zhang-Shasha unit-cost tree-edit distance over parsed `assembly:` trees.")
		fmt.Println("- **type-mismatch** is 1 when host and neighbor differ on `type-in` or `type-out`, else 0.")
		fmt.Println("")
		fmt.Println("Read the breakdown, not the score: a 1-edit neighbor under TED is the chess-opening-tree "+
			"analog (one atom or op swapped). Large Jaccard with low TED means same shape, different atoms.")
		fmt.Println("")
	}
	for _, id := range hosts {
		host := sub[id]
		neighbors := assembly.RankNeighbors(host, sub, w, k)
		if asMarkdown {
			emitNeighborsMarkdown(host, neighbors)
		} else {
			emitNeighborsPlain(host, neighbors)
		}
	}
}

func emitNeighborsPlain(host *types.LexEntry, neighbors []assembly.Neighbor) {
	fmt.Printf("\n%s %s\n", host.ID, host.Name)
	for i, n := range neighbors {
		fmt.Printf("  %d. %s  score=%.3f  (jaccard=%.3f, ted=%d, type-mismatch=%d)\n",
			i+1, n.ID, n.Score, n.Distance.Jaccard, n.Distance.TED, n.Distance.TypeMismatch)
	}
}

func emitNeighborsMarkdown(host *types.LexEntry, neighbors []assembly.Neighbor) {
	fmt.Printf("## %s — %s\n\n", host.ID, host.Name)
	fmt.Printf("- type: `%s → %s`, tier: `%s`\n", host.TypeIn, host.TypeOut, host.Tier)
	if host.Assembly != "" {
		fmt.Printf("- assembly: `%s`\n", host.Assembly)
	}
	fmt.Println("")
	if len(neighbors) == 0 {
		fmt.Println("(no neighbors)")
		fmt.Println()
		return
	}
	fmt.Println("| rank | id | score | jaccard | TED | type-mismatch |")
	fmt.Println("|---|---|---|---|---|---|")
	for i, n := range neighbors {
		fmt.Printf("| %d | %s | %.3f | %.3f | %d | %d |\n",
			i+1, neighborLabel(n), n.Score, n.Distance.Jaccard, n.Distance.TED, n.Distance.TypeMismatch)
	}
	fmt.Println("")
}

func neighborLabel(n assembly.Neighbor) string {
	// We don't have the entry's name handy here without re-passing the
	// elements; compromise: show id only. Markdown table stays
	// scannable.
	return fmt.Sprintf("`%s`", strings.TrimSpace(n.ID))
}
